Set up the test database when running setup or update

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -41,3 +41,25 @@ fi
 
 echo "==> Creating database..."
 bundle exec rails db:setup
+
+echo "==> Dropping test database..."
+set +e
+RAILS_ENV="test" bundle exec rails db:drop
+DB_DROP_RESULT=$?
+set -e
+
+if [ -z "$CI" ] && [ -n "$DB_DROP_RESULT" ]; then
+  printf "\nDatabase drop failed. Continue anyway? [y/N] "
+  read -r
+
+  case $REPLY in
+    y | Y)
+      ;;
+    *)
+      exit 1
+      ;;
+  esac
+fi
+
+echo "==> Creating test database..."
+RAILS_ENV="test" bundle exec rails db:setup
